server:
  port: 11004

spring:
  application:
    name: rocketmq-producer
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ 服务地址
          name-server: 192.168.99.100:9876
        bindings:
          output:
            producer:
              group: producer-group
      bindings:
        output:
          destination: joe-topic
          content-type: application/json

logging:
  level:
    org:
      springframework:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG