spring:
  application:
    name: joe-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: joe-provider
server:
  port: 9998