spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123456
    url: jdbc:mysql://localhost:3306/joe_oauth2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true