server:
  port: 9999
spring:
  application:
    name: joe-provider
#dubbo:
#  scan:
#    base-packages: com.joe.provider.service
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: spring-cloud://localhost
